### ISSUE TITLE
Danger is failing with 403s

### ISSUE THREAD

**Issue by sl0thentr0py** [getsentry/github-workflows#47]
### Environment

https://github.com/getsentry/sentry-ruby/blob/7ec474805aea75c52e2af1a7882d10cfe8ddc028/.github/workflows/danger.yml#L9

### Steps to Reproduce

we started using danger in sentry-ruby recently to enforce changelogs

### Expected Result

danger works

### Actual Result

fails with 403
https://github.com/getsentry/sentry-ruby/actions/runs/3445263716/jobs/5748774925#step:4:59

**Comment by vaind** [comment]
Danger failed in your PR because it found an issue: https://github.com/getsentry/sentry-ruby/pull/1876#discussion_r1020201876

The one printed in the action log output is unrelated and doesn't make the action fail. I know it's confusing, it did confuse me too in the past, but AFAIK there isn't much to do about it other than hiding it from the output. I'll think about what can be done to improve this, e.g. hide the issue from logs, or show actual errors also in logs (If danger can do that, not sure...). For reference, here's danger-js issue related to the error printed in logs: https://github.com/danger/danger-js/issues/1031

**Comment by sl0thentr0py** [comment]
alright, thx @vaind, closing then

**Comment by vaind** [comment]
> @vaind how do I tell danger to ignore this issue, don't particularly care about this right now and all our other actions just use tags on github actions

There's no way to disable specific rules at the moment.
